# Generated by Django 2.2.6 on 2019-10-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20191019_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='plaftform',
            new_name='platform',
        ),
    ]
