# Generated by Django 2.2.6 on 2019-10-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20191019_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_year',
            field=models.IntegerField(verbose_name='release year'),
        ),
    ]
