# Generated by Django 2.2.7 on 2019-11-07 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_auto_20191024_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcopy',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='shows.Show'),
        ),
    ]
