# Generated by Django 2.2.6 on 2019-10-24 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='form',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='platform',
        ),
        migrations.CreateModel(
            name='MovieCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=200, verbose_name='platform')),
                ('form', models.CharField(max_length=200, verbose_name='format')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
    ]
